// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tarea7.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241110005915_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Detenciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaD")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pasaporte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("longitud")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Detenciones");
                });
#pragma warning restore 612, 618
        }
    }
}
